version: '3.4'

services:
  fc.codeflix.catalog.fb:
    container_name: rockethelp_db
    hostname: rockethelp_db
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Rock3tHeIp.@

networks:
  default:
    name: service_rockethelp

    